apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    run: my-service
spec:
  type: NodePort
  ports:
  - port: 5000 
    targetPort: 5000 
    protocol: TCP
    name: http 
  selector:
    run: my-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  selector:
    matchLabels:
      run: my-service
  replicas: 1
  template:
    metadata:
      labels:
        run: my-service
    spec:
      containers:
      - name: myservice
        image: taflagg/myservice:0.0.1
        env: 
          - name: REDIS_ADDR
            value: "127.0.0.1"
          - name: REDIS_PORT
            value: "6379"
        ports:
        - name: myservice-port
          containerPort: 5000 
      - name: redis
        image: redis:alpine
        ports:
          - name: redis-port
            containerPort: 6379 
